# Task 1 

print(np.setxor1d(array1, array2)): The np.setxor1d function returns the sorted symmetric difference between the two input arrays, which consists of elements that are in either ‘array1’ or ‘array2’ but not in both

In [74]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(a, b))

Unique values that are in only one (not both) of the input arrays:
[ 1  3  5  6  7  8  9 10]


# Task 2
Create a NumPy array of integers from 1 to 20
Reshape the array into a 4x5 grid

In [18]:
import numpy as np
array = np.arange(1, 21)
array = array.reshape(4,5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# Task 3
 Define the variable set_dff

 Print the variable set_diff

In [27]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5, 3, 4])
set_diff = np.setdiff1d(b, a)
print(np.append(set_diff, a))

[ 4  6 11 14 19 12  5  7 15  3  1  8]


# Another approach to solving Task 3
Create a set of all elements in array b
create a set() function
Create a new array a that contains all elements of the original array a and any elements of array b that are not already in array a, using the np.append() function and a list comprehension.

In [28]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5, 3, 4])
b_set = set(b)
a = np.append(a, [x for x in b_set if x not in a])
print(a)

[12  5  7 15  3  1  8  4  6 11 14 19]


# Task 4
Transform the 4x5 array shown above in Problem 2.

The numpy. ravel() function is used to create a contiguous flattened array. A 1-D array, containing the elements of the input, is returned.

In [38]:
import numpy as np
x = np.array([[ 1, 2, 3, 4,  5],
             [ 6, 7, 8,  9, 10],
             [11, 12, 13, 14, 15],
             [16, 17, 18, 19, 20]])
y = np.ravel(x)
print("Flattened array:", y)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# Task 5


In [4]:
import pandas
import numpy as np
# suppress scientific notation
np.set_printoptions(suppress = True)
# read the data file from GitHub and convert to a NumPy ndarray object
# be sure to replace the ‘link_to_raw_copy of data file in your Github Repository’ placeholder shown below
# with a link to the “raw” version of the file you pushed to your online GitHub repository
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/Rachael2311/DAV-5400/main/M3_Data.csv').to_numpy()
# verify you have an
type(nyc_water)

numpy.ndarray

# Task 5(i)
Using argmax() to find the max per capital daily water consumption

In [52]:

argmax = np.argmax(nyc_water[:, -1])
argmax
nyc_water[argmax][0]

1979.0

# Another approach to solving Task 5(i)

In [55]:

max_year = nyc_water[nyc_water[:, 2] == np.max(nyc_water[:, 2])]

# Print the year with the maximum per capita daily water consumption
print("Year with maximum per capita daily water consumption:", max_year[0][0])

Year with maximum per capita daily water consumption: 1979.0


# Task 5(ii)

Add a new column to the Numpy array containing the annual change in the population
Calculate the annual change in the population for each year except for the first year

In [8]:
# Add a new column to the Numpy array containing the annual change in the population
nyc_water = np.concatenate((nyc_water, np.zeros((nyc_water.shape[0], 1))), axis=1)

# Calculate the annual change in the population for each year except for the first year
nyc_water[:, 4] = nyc_water[:, 1]-np.roll(nyc_water[:1, 1], -1, axis=0)

# Print the Numpy array with the new column
print(nyc_water)

[[   1979.  7102100.     1512.      213.        0. ]
 [   1980.  7071639.     1506.      213.   -30461. ]
 [   1981.  7089241.     1309.      185.   -12859. ]
 [   1982.  7109105.     1382.      194.     7005. ]
 [   1983.  7181224.     1424.      198.    79124. ]
 [   1984.  7234514.     1465.      203.   132414. ]
 [   1985.  7274054.     1326.      182.   171954. ]
 [   1986.  7319246.     1351.      185.   217146. ]
 [   1987.  7342476.     1447.      197.   240376. ]
 [   1988.  7353719.     1484.      202.   251619. ]
 [   1989.  7344175.     1402.      191.   242075. ]
 [   1990.  7335650.     1424.      194.   233550. ]
 [   1991.  7374501.     1469.      199.   272401. ]
 [   1992.  7428944.     1369.      184.   326844. ]
 [   1993.  7506166.     1368.5     182.   404066. ]
 [   1994.  7570458.     1357.7     179.   468358. ]
 [   1995.  7633040.     1325.7     174.   530940. ]
 [   1996.  7697812.     1297.9     169.   595712. ]
 [   1997.  7773443.     1205.5     155.   671

# Task 5(iii)

Calculating the mean

In [12]:

med_pol = np.median(nyc_water[:, 1])
print("Median:",med_pol)


Median: 7947660.0


# Calculating the variance
pol means population

In [5]:
import numpy as np
var_pol = np.var(nyc_water[:, 1])
print("Variance is:",var_pol)

Variance is: 214014109798.73172


# Task 5(iv)

What was the average annual change in the population of the city?

In [11]:
Avg_annual_change = np.average(nyc_water[:, 4])
print("The average is:", Avg_annual_change)

The average is: 705980.5
